name: Flutter CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - uses: actions/checkout@v4

      # Setup Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.1' # set your version

      # Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Fetch latest GitHub release and update pubspec.yaml
      - name: Set pubspec version to latest release + PR number
        env:
          GITHUB_PR_NUMBER: ${{ github.event.pull_request.number }}
          GITHUB_RUN_NUMBER: ${{ github.run_number }}
        run: |
          echo "Fetching latest release from GitHub..."
          LATEST=$(curl -s https://api.github.com/repos/YOUR_ORG/YOUR_REPO/releases/latest | jq -r '.tag_name' | sed 's/v//')
          echo "Latest release version: $LATEST"
          BUILD_NUMBER="${GITHUB_PR_NUMBER}.${GITHUB_RUN_NUMBER}"
          echo "Setting version: $LATEST+$BUILD_NUMBER"
          sed -i "s/^version:.*/version: $LATEST+$BUILD_NUMBER/" pubspec.yaml
          cat pubspec.yaml | grep version:

      # Analyze code
      - name: Analyze code
        run: flutter analyze

      # Run tests
#      - name: Run tests
#        run: flutter test --coverage

      # Build APK
      - name: Build APK
        run: flutter build apk --release

      # Upload APK artifact
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: pr-apk
          path: build/app/outputs/flutter-apk/app-release.apk
