name: Release (Tag Driven)

on:
  push:
    tags:
      - 'v*.*.*'   # e.g. v1.2.3

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'

      - name: Install dependencies
        run: flutter pub get

      - name: Set pubspec.yaml version from tag
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "Setting pubspec.yaml version to $VERSION"
          sed -i "s/^version:.*/version: $VERSION+1/" pubspec.yaml
          cat pubspec.yaml | grep version:

      - name: Build APK
        run: flutter build apk --release

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          files: build/app/outputs/flutter-apk/app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
